### ISSUE TITLE
error using apt update_cache: true

### ISSUE THREAD

**Issue by drewmullen** [geerlingguy/docker-debian9-ansible#7]
I'm getting an error when i use apt `update_cache: true`: 
> "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file."}

Theres a similar issue on ansible/ansible but its been open for years so im curious if you've encountered this and how you got around it? https://github.com/ansible/ansible/issues/30754

currently i can get around this by manually running `command: apt update` sub-sequential `apt update_cache=true` commands succeed after that but this is ugly and feels icky

**Comment by geerlingguy** [comment]
Strange, I have not had this issue on any of my playbook tests. Can you provide a configuration / playbook that reproduces this scenario?

**Comment by drewmullen** [comment]
after retrying the same configuration today its working without the work-around (manually auto updating). i'm going to chalk this one up to repo issues

in case you ever see anything like this again in the future (hello to future self?) the config was straightforward: 
- fresh molecule role
- sub in your container 
```
  platforms:
    - name: instance
      image: geerlingguy/docker-debian9-ansible
      pre_build_image: true
```

run simple play
```
    - name: install packages
      apt:
         state: present
         name: "{{ item }}"
         update_cache: true
      with_items:
        - "vim"
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "gnupg2"
        - "software-properties-common"
        - "groff"
```

`molecule converge`
